version: 2.1

aliases:
  - &defaults
    docker:
      - image: circleci/node:10
    working_directory: ~/source

  - &restore_cache
    restore_cache:
      keys:
        - npm-deps-{{ checksum "package.json" }}

  - &save_cache
    save_cache:
      key: npm-deps-{{ checksum "package.json" }}
      paths:
        - node_modules

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: sudo npm i -g npm@6.2.0
      - run: npm ci
      - *save_cache

  eslint:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm run eslint

  unit:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm run test
workflows:
  version: 2
  all:
    jobs:
      - setup
      - eslint:
          requires:
            - setup
      - unit:
          requires:
            - setup
